twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        env: '%kernel.environment%'
        game_type: '%game_type%'
        game_status: '%game_status%'

when@test:
    twig:
        strict_variables: true
